title: Stefan Subich
tagline: >-
  "I can figure it out."
description: >-
  Software Engineer and technology enthusiast.
baseurl: ""
repository: subich/subich.github.io
open_new_tab: false # Opens external URLs in new tab (works for posts, projects and navbar only)

plugins:
  - jemoji

nav_exclude: # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md

author:
  name: Stefan Subich
  image: /assets/me.jpeg
  email: s@subich.dev
  github: subich
  linkedin: subich
  mastodon: stefn

### Posts ###
permalink: /blog/:title

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"

exclude:
  - "*.log"
  - "vendor"
